
include:
  - board: nice_nano_v2
    shield: corne_peripheral_left nice_view_adapter nice_view
    
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view

  - board: nice_nano_v2
    shield: settings_reset

  - board: nice_nano_v2
    shield: corne_dongle
  
